```{r, message=False}
library(glue)
library(data.table)
library(ldlinkR)
library(stringr)
library(lme4)
library(mvnfast)
setwd("/scratch/network/cs9095/cs551")
source("walmart_robin.R")
```


```{r}
gene <- "ENSG00000213390"
robin_df <- fread(glue("merged_data/{gene}_merge.tsv"))
names(robin_df) <- c("snp", "gwas_b", "gwas_se", "eqtl_b", "eqtl_se")
setorder(robin_df, cols="snp")

# ld <- fread(glue("{gene}_LD.tsv"))
# ld <- subset(ld, select = -c(RS_number))
# ld <- as.matrix(ld)
# dimnames(ld) <- list(unlist(dimnames(ld)[2]), unlist(dimnames(ld)[2]))
# ld <- ld[1:10,1:10]



# walmart_robin(robin_df, n_replicates, ld)

```

```{r}
out_pval <- c() 
goi <- c('ENSG00000053918',
 'ENSG00000082438',
 'ENSG00000119912',
 'ENSG00000132170',
 'ENSG00000138190',
 'ENSG00000145996',
 'ENSG00000148737',
 'ENSG00000151465',
 'ENSG00000164758',
 'ENSG00000168297',
 'ENSG00000168944',
 'ENSG00000173175',
 'ENSG00000176399',
 'ENSG00000197157',
 'ENSG00000213390')



n_replicates <- 1000

for (gene in goi) {
    robin_df <- fread(glue("merged_data/{gene}_merge.tsv"))
    names(robin_df) <- c("snp", "gwas_b", "gwas_se", "eqtl_b", "eqtl_se")
    setorder(robin_df, cols="snp")
    output <- walmart_robin(robin_df, n_replicates, ld)
    out_pval <- append(out_pval, output)
}



```

```{r}
out_pval
```


```{r}
eqtl_se = robin_df$eqtl_se
eqtl_b = robin_df$eqtl_b
gwas_b = robin_df$gwas_b
snp = robin_df$snp

ld_len <- length(unique(snp))
ld <- diag(ncol=ld_len, nrow=ld_len)

```

```{r}
# Model does not fit an intercept, either random or fixed
me_fit = lmer(eqtl_b~-1+gwas_b+(gwas_b-1|snp), 
            weights=1/eqtl_se^2)
t_stat = summary(me_fit)$coefficients[3]
```



```{r}
temp = subset(robin_df, select = -c(eqtl_b, eqtl_se))
temp <- temp[!duplicated(temp)]
gwas_se = temp$gwas_se

sigma_gwas = (gwas_se %*% t(gwas_se)) * ld
# sigma_gwas = diag(gwas_se) %*% ld %*% diag(gwas_se)

# sigma_gwas == diag(gwas_se) %*% ld %*% diag(gwas_se)


null_gwas_b = rmvn(n=n_replicates, mu=rep(0, length(gwas_se)), 
                    sigma=sigma_gwas) # n_replicates x p (unique SNPs) matrix

colnames(null_gwas_b) = unique(robin_df$snp)
t_nulls = numeric(n_replicates)
print(null_gwas_b)
```


```{r}
for (r in 1:n_replicates) {
# Suppress convergence issue warnings 
suppressWarnings({null_fit = lmer(eqtl_b~-1+null_gwas_b[r,snp]+
                                    (null_gwas_b[r,snp]-1|snp),
                                    weights=1/eqtl_se^2)})
t_nulls[r] = summary(null_fit)$coefficients[3]
}

p_val = sum(abs(t_nulls) > abs(t_stat))/n_replicates
return(p_val)

```

```{r}
p_val
```


